spring:
  application:
    name: med_api

  datasource:
    url: jdbc:mysql://${DB_HOST}/med_api
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # show stack trace and format sql details
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

 # prevent the exception stack tracer
server:
  error:
    include-stacktrace: never

# Config JWT
jwt:
  secret-key: ${JWT_KEY}