spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  # show stack trace and format sql details
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
